name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger on pushes to the main branch
  pull_request:   # Trigger on pull requests to the main branch
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # The environment to run the pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Pull the latest code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install   # Install project dependencies

      - name: Run tests
        run: npm test   # Run unit tests

      - name: Build the application
        run: npm run build   # Build the application (if required)

      - name: Deploy to production
        run: ./deploy.sh   # Script to deploy the application
